# This module defines a base Pydantic model for tangible products, encapsulating
# common attributes that are shared across different types of hardware like drives,
# motors, etc. By creating a common base model, we ensure consistency,
# reduce code duplication, and improve maintainability of product-related models.

from __future__ import annotations

from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, BeforeValidator, Field, computed_field
from typing_extensions import Annotated


from datasheetminer.models.common import ProductType, ValueUnit
from datasheetminer.placeholders import is_placeholder


def _coerce_placeholder_to_none(v: Any) -> Any:
    """Replace placeholder strings ("N/A", "TBD", ...) with None at ingest.

    Keeps the database free of "N/A" literals, which would otherwise inflate
    quality scores and render as garbage in the frontend table.
    """
    return None if is_placeholder(v) else v


PlaceholderSanitizedStr = Annotated[
    Optional[str],
    BeforeValidator(_coerce_placeholder_to_none),
]


class Dimensions(BaseModel):
    """Represents physical dimensions of an object."""

    width: Optional[float] = None
    length: Optional[float] = None
    height: Optional[float] = None
    unit: Optional[str] = "mm"


class ProductBase(BaseModel):
    """
    A base model for products with common attributes, designed for DynamoDB.

    This model uses a composite primary key (PK, SK) to align with DynamoDB's
    single-table design best practices.

    Attributes:
        PK: The Partition Key. Formatted as 'PRODUCT#<product_type>'.
        SK: The Sort Key. Formatted as 'PRODUCT#<product_id>'.
        product_id: The unique identifier (UUID) for the product.
    """

    model_config = {"populate_by_name": True}

    @computed_field
    def PK(self) -> str:
        return f"PRODUCT#{self.product_type.upper()}"

    @computed_field
    def SK(self) -> str:
        return f"PRODUCT#{self.product_id}"

    # AI-generated comment: product_id is auto-generated by the program, not by the LLM.
    # Making it Optional ensures the LLM won't try to create UUIDs, which it does incorrectly.
    # The default_factory ensures a UUID is always generated if not provided.
    product_id: UUID = Field(
        default_factory=uuid4, description="Unique identifier (auto-generated)"
    )
    product_type: ProductType = Field(
        ..., description="Type of product (e.g., 'motor', 'drive')"
    )
    product_name: str = Field(..., description="Product name")
    product_family: PlaceholderSanitizedStr = Field(
        None, description="Product family or sub-series"
    )
    part_number: PlaceholderSanitizedStr = Field(None, description="Part number")
    manufacturer: str = Field(..., description="Manufacturer name")
    release_year: Optional[int] = None
    dimensions: Optional[Dimensions] = None
    weight: Optional[ValueUnit] = None
    msrp: Optional[ValueUnit] = None
    msrp_source_url: Optional[str] = Field(
        None,
        description="URL the MSRP was scraped from. Populated by price-enrich.",
    )
    msrp_fetched_at: Optional[str] = Field(
        None, description="ISO 8601 timestamp when MSRP was last fetched."
    )
    warranty: Optional[ValueUnit] = None
    datasheet_url: Optional[str] = Field(
        None, description="URL of the source datasheet"
    )
    pages: Optional[list[int]] = Field(
        None,
        description="1-indexed PDF pages where this product's specs were found. Used for #page=N deep-linking.",
    )
