#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -e

if [[ "${TRACE-0}" == "1" ]]; then
    set -o xtrace
fi

# Function to display help
help_function() {
    cat <<EOF

Usage: $(basename "$0") [-h] [--lib-dir LIB_DIR]

Options:
  -h, --help       Display this help message and exit
  --lib-dir        Optional path to the lib/ directory
  -f, --function   Name of the lambda function

EOF
}

# Function to check if a command exists
command_exists() {
    if command -v "$1" >/dev/null 2>&1; then
        return 0
    else
        echo "'$1' not found."
        return 1
    fi
}

# Check required dependencies
check_dependencies() {
    if ! command_exists uv; then
        cat <<EOF

uv is not installed. Install it using:

    curl -LsSf https://astral.sh/uv/install.sh | sh

EOF
        exit 1
    fi

    if ! command_exists sam; then
        cat <<EOF

AWS SAM CLI is not installed or not in your PATH. Install it with:

Linux:

wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip && \\
    unzip aws-sam-cli-linux-x86_64.zip -d sam-installation && \\
    sudo ./sam-installation/install && \\
    rm -rf aws-sam-cli-linux-x86_64.zip sam-installation

macOS:

brew tap aws/tap && \\
    brew install aws-sam-cli

EOF
        exit 1
    fi
}

# Main function of the script
main() {
    local FUNCTION="datasheetminer"

    # Parse arguments
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
            -h|--help)
                help_function
                exit 0
                ;;
            -f|--function)
                FUNCTION="$2"
                shift 2
                ;;
            *)
                echo "Unknown parameter passed: $1"
                help_function
                exit 1
                ;;
        esac
    done

    check_dependencies

    PROMPT="Identify the individual components along with their key specifications. Use this schema: $(cat SCHEMA.md) to capture the important characteristics based on the information provided. Outline the schema as a JSON object. Create a list of JSON objects like this one for each product found."

    uv run datasheetminer --prompt "$PROMPT" --url "https://acim.nidec.com/drives/control-techniques/-/media/Project/Nidec/ControlTechniques/Documents/en-en/Digitax-HD-Brochure-EN-Web.pdf" --pages 28,29,33,35
    exit 0

    . .env
    # awscurl -X POST --service lambda  -H "Content-Type: application/json" -H "x-api-key: $GEMINI_API_KEY" -d '{"prompt": "Identify the products and technologies along with key specifications. Devise a schema that could capture the important characteristics based on the information provided. Outline the schema as a JSON object. Create a list of JSON objects like this one that can be used to create an initial seed for a database to ingest.", "url": "https://acim.nidec.com/drives/control-techniques/-/media/Project/Nidec/ControlTechniques/Documents/Datasheets/Digitax-HD-Datasheet.pdf"}' https://8bol76pnte.execute-api.us-east-1.amazonaws.com/Prod/hello

    # Deploy updates to AWS
    echo "Updating endpoint..."
    uv run ruff format && \
        PYTHONPATH="datasheetminer" uv run pytest tests/unit && \
        sam validate --lint && \
        sam build && \
        sam deploy && \
        PYTHONPATH="datasheetminer" uv run pytest tests/integration
}

main "$@"
