/**
 * Type definitions matching the backend API.
 *
 * ⚠ MIGRATION IN PROGRESS — see todo/PYTHON_BACKEND.md (Phase 0a).
 *
 * The Pydantic-derived TypeScript interfaces now live in `./generated.ts`,
 * regenerated by `./Quickstart gen-types`. CI fails when that file drifts
 * from `specodex/models/*.py`.
 *
 * The interfaces below are still hand-typed because the generated shapes
 * differ from what the frontend currently expects (`product_id` is optional
 * in generated, `product_name` is required, nullable fields carry `| null`,
 * `Manufacturer.PK` is required, `datasheet_url` is `string` not the
 * frontend's `DatasheetLink` object). Migrating each interface needs a
 * paired pass through its consumers, not a blind re-export — track each
 * sub-step under PYTHON_BACKEND.md Phase 0a.
 *
 * Frontend-only view types (`DatasheetEntry`, `DatasheetLink`,
 * `ProductSummary`) stay hand-typed permanently — they are not Pydantic
 * models.
 */

export interface ValueUnit {
  value: number;
  unit: string;
}

export interface MinMaxUnit {
  min: number;
  max: number;
  unit: string;
}

export interface DatasheetLink {
  url: string;
  pages?: number[];
}

export interface Dimensions {
  length?: ValueUnit;
  width?: ValueUnit;
  height?: ValueUnit;
}

export interface ProductBase {
  product_id: string;
  product_type: string;
  product_name?: string;
  manufacturer: string;
  part_number?: string;
  datasheet_url?: DatasheetLink;
  dimensions?: Dimensions;
  weight?: ValueUnit;
  // Expected delivery / lead time. Mirrors specodex/models/product.py
  // ProductBase.lead_time — typically a ValueUnit with unit='days'.
  lead_time?: ValueUnit;
  PK: string;
  SK: string;
}

export type MotorType =
  | 'brushless dc'
  | 'brushed dc'
  | 'ac induction'
  | 'ac synchronous'
  | 'ac servo'
  | 'permanent magnet'
  | 'hybrid';

export interface Motor extends ProductBase {
  product_type: 'motor';
  type?: MotorType;
  series?: string;
  rated_voltage?: MinMaxUnit;
  rated_speed?: ValueUnit;
  rated_torque?: ValueUnit;
  peak_torque?: ValueUnit;
  rated_power?: ValueUnit;
  encoder_feedback_support?: string;
  poles?: number;
  rated_current?: ValueUnit;
  peak_current?: ValueUnit;
  voltage_constant?: ValueUnit;
  torque_constant?: ValueUnit;
  resistance?: ValueUnit;
  inductance?: ValueUnit;
  ip_rating?: number;
  rotor_inertia?: ValueUnit;
  shaft_diameter?: ValueUnit;
  frame_size?: string;
}

export type DriveType = 'servo' | 'variable frequency';

/**
 * Ethernet-based industrial fieldbus protocols supported on drives.
 */
export type CommunicationProtocol =
  | 'EtherCAT'
  | 'EtherNet/IP'
  | 'PROFINET'
  | 'Modbus TCP'
  | 'POWERLINK'
  | 'Sercos III'
  | 'CC-Link IE';

export interface Drive extends ProductBase {
  product_type: 'drive';
  type?: DriveType;
  series?: string;
  input_voltage?: MinMaxUnit;
  input_voltage_frequency?: (ValueUnit | MinMaxUnit)[];
  input_voltage_phases?: number[];
  rated_current?: ValueUnit;
  peak_current?: ValueUnit;
  rated_power?: ValueUnit;
  switching_frequency?: (ValueUnit | MinMaxUnit)[];
  fieldbus?: CommunicationProtocol[];
  control_modes?: string[];
  encoder_feedback_support?: string[];
  ethernet_ports?: number;
  digital_inputs?: number;
  digital_outputs?: number;
  analog_inputs?: number;
  analog_outputs?: number;
  safety_features?: string[];
  safety_rating?: string[];
  approvals?: string[];
  max_humidity?: number;
  ip_rating?: number;
  operating_temp?: MinMaxUnit;
}

export interface RobotArm extends ProductBase {
  product_type: 'robot_arm';
  product_family?: string;
  payload?: ValueUnit;
  reach?: ValueUnit;
  degrees_of_freedom?: number;
  pose_repeatability?: ValueUnit;
  max_tcp_speed?: ValueUnit;
  ip_rating?: number;
  cleanroom_class?: string;
  noise_level?: ValueUnit;
  mounting_position?: string;
  operating_temp?: MinMaxUnit;
  materials?: string[];
  safety_certifications?: string[];
}

export interface Gearhead extends ProductBase {
  product_type: 'gearhead';
  gear_ratio?: number;
  gear_type?: string;
  stages?: number;
  nominal_input_speed?: ValueUnit;
  max_input_speed?: ValueUnit;
  rated_torque?: ValueUnit;
  peak_torque?: ValueUnit;
  backlash?: ValueUnit;
  efficiency?: number;
  torsional_rigidity?: ValueUnit;
  rotor_inertia?: ValueUnit;
  noise_level?: ValueUnit;
  frame_size?: string;
  input_shaft_diameter?: ValueUnit;
  output_shaft_diameter?: ValueUnit;
  max_radial_load?: ValueUnit;
  max_axial_load?: ValueUnit;
  ip_rating?: number;
  operating_temp?: MinMaxUnit;
  service_life?: ValueUnit;
  lubrication_type?: string;
}

export interface DatasheetEntry extends ProductBase {
  product_type: 'datasheet';
  component_type?: string; // The actual type of the component (e.g. 'motor', 'drive')
  product_family?: string;
  url: string;
  pages?: number[];
  is_scraped?: boolean;
}

export interface LinearActuator extends ProductBase {
  product_type: 'linear_actuator';
  type?: 'linear_slide' | 'linear_stage' | 'rodless_screw' | 'rodless_belt' | 'lm_guide_actuator';
  series?: string;
  stroke?: ValueUnit;
  max_work_load?: ValueUnit;
  max_push_force?: ValueUnit;
  holding_force?: ValueUnit;
  dynamic_load_rating?: ValueUnit;
  static_load_rating?: ValueUnit;
  max_linear_speed?: ValueUnit;
  max_acceleration?: ValueUnit;
  positioning_repeatability?: ValueUnit;
  backlash?: ValueUnit;
  actuation_mechanism?: 'ball_screw' | 'lead_screw' | 'belt' | 'linear_motor';
  lead_screw_pitch?: ValueUnit;
  screw_diameter?: ValueUnit;
  static_allowable_moment_pitching?: ValueUnit;
  static_allowable_moment_yawing?: ValueUnit;
  static_allowable_moment_rolling?: ValueUnit;
  rotor_inertia?: ValueUnit;
  motor_type?: 'step_motor' | 'servo_motor' | 'motorless';
  encoder_feedback_support?: string[];
  rated_voltage?: MinMaxUnit;
  rated_current?: ValueUnit;
  peak_current?: ValueUnit;
  rated_power?: ValueUnit;
  ip_rating?: number;
  operating_temp?: MinMaxUnit;
  operating_humidity_range?: ValueUnit;
  cleanroom_class?: string;
}

export type Product = Motor | Drive | RobotArm | Gearhead | LinearActuator | DatasheetEntry;
export type ProductType = 'motor' | 'drive' | 'robot_arm' | 'gearhead' | 'contactor' | 'electric_cylinder' | 'linear_actuator' | 'datasheet' | 'all' | null;

/**
 * Product summary with dynamic counts per type
 * The backend returns counts for all product types dynamically
 * e.g., { total: 10, motors: 5, drives: 3, robot_arms: 2 }
 */
export interface ProductSummary {
  total: number;
  [key: string]: number; // Dynamic property for each product type count (e.g., motors, drives, robot_arms)
}
